name: resman_mobile_customer
description: Mobile application for Restaurant Management project
version: 1.0.0
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_images_slider: ^0.0.2
  flutter_vector_icons: ^0.1.0
  gradient_widgets: ^0.4.1
  intl: ^0.15.8
  shared_preferences: ^0.5.2
  equatable: ^0.1.6
  bloc: ^0.13.0
  rxdart: ^0.22.0
  flutter_bloc: ^0.13.0
  image_picker: ^0.6.2+3
  firebase_storage: ^3.0.0
  pull_to_refresh: ^1.4.3
  cached_network_image: ^2.0.0-rc
  flutter_svg: ^0.14.4
  dashed_container: ^1.0.1
  material_design_icons_flutter: ^3.4.4595
  marquee: ^1.3.1
  timeago: ^2.0.22
  flutter_money_formatter: ^0.8.3
  like_button: ^0.1.9
  toast: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Rukola
      fonts:
        - asset: assets/fonts/iciel-rukola.otf
  assets:
    - assets/icons/
    - assets/images/
